[2025-05-10T03:43:36.224+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-10T03:43:36.288+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_price_btc_price_by_day.save_to_db manual__2025-05-10T03:36:23.870266+00:00 [queued]>
[2025-05-10T03:43:36.308+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_price_btc_price_by_day.save_to_db manual__2025-05-10T03:36:23.870266+00:00 [queued]>
[2025-05-10T03:43:36.309+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-05-10T03:43:36.336+0000] {taskinstance.py:2327} INFO - Executing <Task(_PythonDecoratedOperator): save_to_db> on 2025-05-10 03:36:23.870266+00:00
[2025-05-10T03:43:36.349+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-10T03:43:36.357+0000] {standard_task_runner.py:63} INFO - Started process 88 to run task
[2025-05-10T03:43:36.358+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'get_price_btc_price_by_day', 'save_to_db', 'manual__2025-05-10T03:36:23.870266+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/get_price_btc_price_by_day.py', '--cfg-path', '/tmp/tmpw5y_d47n']
[2025-05-10T03:43:36.365+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask save_to_db
[2025-05-10T03:43:36.555+0000] {task_command.py:426} INFO - Running <TaskInstance: get_price_btc_price_by_day.save_to_db manual__2025-05-10T03:36:23.870266+00:00 [running]> on host 840719eb5226
[2025-05-10T03:43:36.863+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_price_btc_price_by_day' AIRFLOW_CTX_TASK_ID='save_to_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-10T03:36:23.870266+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-10T03:36:23.870266+00:00'
[2025-05-10T03:43:36.865+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-10T03:43:36.886+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-10T03:43:36.913+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_price_btc_price_by_day.py", line 56, in save_to_db
    target_engine = get_postgres_sqlalchemy_engine("etl_db")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/db.py", line 12, in get_postgres_sqlalchemy_engine
    connection = BaseHook.get_connection(conn_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `etl_db` isn't defined
[2025-05-10T03:43:36.923+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_price_btc_price_by_day, task_id=save_to_db, execution_date=20250510T033623, start_date=20250510T034336, end_date=20250510T034336
[2025-05-10T03:43:36.957+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task save_to_db (The conn_id `etl_db` isn't defined; 88)
[2025-05-10T03:43:37.002+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-10T03:43:37.044+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-10T03:43:37.047+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
