[2025-05-10T03:36:28.543+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-10T03:36:28.604+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_price_btc_price_by_day.save_to_db manual__2025-05-10T03:36:23.870266+00:00 [queued]>
[2025-05-10T03:36:28.621+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_price_btc_price_by_day.save_to_db manual__2025-05-10T03:36:23.870266+00:00 [queued]>
[2025-05-10T03:36:28.622+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-10T03:36:28.650+0000] {taskinstance.py:2327} INFO - Executing <Task(_PythonDecoratedOperator): save_to_db> on 2025-05-10 03:36:23.870266+00:00
[2025-05-10T03:36:28.659+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-10T03:36:28.661+0000] {standard_task_runner.py:63} INFO - Started process 83 to run task
[2025-05-10T03:36:28.663+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'get_price_btc_price_by_day', 'save_to_db', 'manual__2025-05-10T03:36:23.870266+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/get_price_btc_price_by_day.py', '--cfg-path', '/tmp/tmpeh421ec1']
[2025-05-10T03:36:28.668+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask save_to_db
[2025-05-10T03:36:28.818+0000] {task_command.py:426} INFO - Running <TaskInstance: get_price_btc_price_by_day.save_to_db manual__2025-05-10T03:36:23.870266+00:00 [running]> on host 840719eb5226
[2025-05-10T03:36:29.102+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_price_btc_price_by_day' AIRFLOW_CTX_TASK_ID='save_to_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-10T03:36:23.870266+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-10T03:36:23.870266+00:00'
[2025-05-10T03:36:29.104+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-10T03:36:29.105+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-10T03:36:29.106+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_price_btc_price_by_day.py", line 55, in save_to_db
    target_engine = get_postgres_sqlalchemy_engine("etl_db")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'get_postgres_sqlalchemy_engine' is not defined
[2025-05-10T03:36:29.139+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_price_btc_price_by_day, task_id=save_to_db, execution_date=20250510T033623, start_date=20250510T033628, end_date=20250510T033629
[2025-05-10T03:36:29.164+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task save_to_db (name 'get_postgres_sqlalchemy_engine' is not defined; 83)
[2025-05-10T03:36:29.202+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-10T03:36:29.244+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-10T03:36:29.246+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
