[2025-05-10T03:31:18.182+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-10T03:31:18.243+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_price_btc_price_by_day.get_data manual__2025-05-10T03:28:38.622295+00:00 [queued]>
[2025-05-10T03:31:18.257+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_price_btc_price_by_day.get_data manual__2025-05-10T03:28:38.622295+00:00 [queued]>
[2025-05-10T03:31:18.258+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-05-10T03:31:18.287+0000] {taskinstance.py:2327} INFO - Executing <Task(_PythonDecoratedOperator): get_data> on 2025-05-10 03:28:38.622295+00:00
[2025-05-10T03:31:18.295+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=53) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-10T03:31:18.297+0000] {standard_task_runner.py:63} INFO - Started process 55 to run task
[2025-05-10T03:31:18.301+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'get_price_btc_price_by_day', 'get_data', 'manual__2025-05-10T03:28:38.622295+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/get_price_btc_price_by_day.py', '--cfg-path', '/tmp/tmpbsobc2gr']
[2025-05-10T03:31:18.305+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask get_data
[2025-05-10T03:31:18.413+0000] {task_command.py:426} INFO - Running <TaskInstance: get_price_btc_price_by_day.get_data manual__2025-05-10T03:28:38.622295+00:00 [running]> on host 840719eb5226
[2025-05-10T03:31:18.653+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_price_btc_price_by_day' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-10T03:28:38.622295+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-10T03:28:38.622295+00:00'
[2025-05-10T03:31:18.656+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-10T03:31:18.658+0000] {logging_mixin.py:188} INFO - Данные за период с 2025-05-08 21:00:00+00:00 по 2025-05-09 21:00:00+00:00
[2025-05-10T03:31:19.052+0000] {logging_mixin.py:188} INFO - {'symbol': 'BTCUSDT', 'lastPrice': '103030.40', 'indexPrice': '103061.81', 'markPrice': '103030.40', 'prevPrice24h': '102598.60', 'price24hPcnt': '0.004208', 'highPrice24h': '104330.10', 'lowPrice24h': '102264.10', 'prevPrice1h': '102950.20', 'openInterest': '46858.622', 'openInterestValue': '4827862568.11', 'turnover24h': '8361929260.1588', 'volume24h': '81144.7340', 'fundingRate': '0.0001', 'nextFundingTime': '1746864000000', 'predictedDeliveryPrice': '', 'basisRate': '', 'deliveryFeeRate': '', 'deliveryTime': '0', 'ask1Size': '6.324', 'bid1Price': '103030.30', 'ask1Price': '103030.40', 'bid1Size': '4.545', 'basis': '', 'preOpenPrice': '', 'preQty': '', 'curPreListingPhase': ''}
[2025-05-10T03:31:19.053+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-10T03:31:19.055+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_price_btc_price_by_day.py", line 40, in get_data
    'last_price': float(data['last_price']),
                        ~~~~^^^^^^^^^^^^^^
KeyError: 'last_price'
[2025-05-10T03:31:19.081+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_price_btc_price_by_day, task_id=get_data, execution_date=20250510T032838, start_date=20250510T033118, end_date=20250510T033119
[2025-05-10T03:31:19.107+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task get_data ('last_price'; 55)
[2025-05-10T03:31:19.131+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-10T03:31:19.186+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-10T03:31:19.193+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
